TestValue: 21
SupplyDepot:
    first: 14     # build the first supply depot at supply level 14
    second: 20    # build the second supply depot at supply level 20
    third: 1
Barracks:
    first: 16     # build the first barracks at supply level 16
    second: 19
    third: 23
Refinery:
    first: 16     # build the first refinery at supply level 16
CommandCenter:
    second: 19     # build command center at supply level 19
SCV:
    scout:
        first: 17   # send the 17th SCV to scout
