SupplyDepot:
    first: 10
    second: 15
    third: 28
    cont: 30
Barracks:
    supplyToBuildAt: [12, 19, 19]
Refinery:
    first: 13     # build the first refinery at supply level 16
CommandCenter:
    second: 50     # build command center at supply level 19
    maxSimulScouts: 4
SCV:
    scout:
        first: 17   # send the 17th SCV to scout
EngineeringBay:
    minSupply: 45 # minimum supply level to build the engineering bay at
    maxSupply: 50 # maximum supply level to build the engineering bay at
    first: 30
Medivac:
    maxUnits: 2   # maximum number of medivacs to have at a time
AttackTrigger:
    timeSeconds: 450 # number of seconds of game time to trigger an attack at
    armyUnits: 50 # number of army units to trigger an attack at
Defend:
    radius: 20 # radius around our command center to defend
Stimpack:
    minHealth: 0.8 # minimum health of a unit to use stimpack
    maxDistanceToEnemy: 20 # maximum distance to the enemy to use stimpack