language: cpp

env: 
 - BUILD_CONFIGURATION=Debug
 - BUILD_CONFIGURATION=Release

os: 
 - windows
 - linux
 - osx

dist: bionic

osx_image: xcode11.4

install:
  - ./.travis/install.sh

script:
  - ./.travis/build.sh
  - ./.travis/publish.sh

deploy:
  provider: pages
  strategy: git
  token: $GITHUB_TOKEN
  local_dir: website/
  edge: true
  on:
    branch: master
    condition: $TRAVIS_OS_NAME = linux && $BUILD_CONFIGURATION = Debug
